# Generated by Django 4.0.1 on 2022-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
