# Generated by Django 4.0.1 on 2022-01-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_customerorders_quantity_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order_id',
            field=models.CharField(max_length=22),
        ),
    ]
