# Generated by Django 4.0.1 on 2022-01-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becamebad',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
